language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.*
  - SYMFONY_VERSION=dev-master

before_script:
  - echo "memory_limit=2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer self-update -v
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update -v
  - composer update -v

script:
  - phpunit

notifications:
  email:
    - software@opticsplanet.com

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
    - env: SYMFONY_VERSION=3.*
    - php: hhvm
